version: '3'

services:
  kong:
    image: kong:2
    restart: always
    networks:
      - usekong
    ports:
      - 443:8443
    env_file: .env
    volumes:
      - ./data/kong/configs/production.yml:/usr/local/kong/declarative/kong.yml
      - ./data/kong/certs:/usr/local/kong/certs:ro
  push:
    image: ghcr.io/tooot-app/push:latest
    restart: always
    networks:
      - usekong
    env_file: ./packages/push/.env
  translate:
    image: ghcr.io/tooot-app/translate:latest
    restart: always
    networks:
      - usekong
    env_file: ./packages/translate/.env

networks:
  usekong:
